### ISSUE TITLE
zabbix 2.4.4 compatibility

### ISSUE THREAD

**Issue by hit0ri** [jhooyberghs/dashing-zabbix#1]
Does it work with zabbix 2.4.4? On zabbix server I can see that the user I'm using for this dashboard is logged in but for some reason it doesn't show any triggers on dashboard.

`dashing start` output:

```
[vagrant@dashing dashing]$ dashing start
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
192.168.33.1 - - [24/Mar/2015 03:18:12] "GET / HTTP/1.1" 302 - 0.0030
192.168.33.1 - - [24/Mar/2015 03:18:12] "GET /default HTTP/1.1" 200 4048 0.0068
192.168.33.1 - - [24/Mar/2015 03:18:13] "GET /views/text.html HTTP/1.1" 200 175 0.0166
192.168.33.1 - - [24/Mar/2015 03:18:13] "GET /views/zabbix.html HTTP/1.1" 200 438 0.0157
192.168.33.1 - - [24/Mar/2015 03:18:13] "GET /views/zabbix_list.html HTTP/1.1" 200 383 0.0100
192.168.33.1 - - [24/Mar/2015 03:28:02] "GET /events HTTP/1.1" 200 - 589.7157
```

screenshot:
![screenshot:](http://a.pomf.se/piqivy.png)

**Comment by jhooyberghs** [comment]
Hey hit0ri, I just tried this with our own zabbix 2.4.4 and it does work for me.

My best guess is that you probably don't have the same "Host Group" names as I do. In the jobs/zabbix.rb file, you can change them to make it fit your environment. It's located just after the login parameters:
SCREENS = {
        "Servers" => [ "DMZ Servers", "Lan Servers", "Linux Servers" ],
        "Network" => [ "Network Devices", "Management", "Printers" ]
}

Hope this helps.

**Comment by hit0ri** [comment]
Yes, that's definitely it!
Thanks
